# Use an official Node.js runtime as a base image
FROM ubuntu:latest

# Install OpenJDK 11
RUN apt update && \
    apt install openjdk-17-jdk -y

# Install Google Cloud SDK
RUN apt-get install apt-transport-https ca-certificates gnupg curl sudo -y && \
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg && \
    echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    apt-get update && sudo apt-get install google-cloud-cli -y

RUN curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && \
    apt-get install -y nodejs

# Set environment variables
ENV JAVA_HOME /usr/lib/jvm/java-13-openjdk-amd64
ENV PATH $PATH:$JAVA_HOME/bin
